# https://github.com/crate-ci/typos
# install:  cargo install typos-cli
# run:      typos

[default.extend-words]
egui = "egui"
rustfmt = "rustfmt"
Rustfmt = "Rustfmt"
RUSTFLAGS = "RUSTFLAGS"
RUSTDOCFLAGS = "RUSTDOCFLAGS"
libgtk = "libgtk"
libsoup = "libsoup"
libjavascriptcoregtk = "libjavascriptcoregtk"
libappindicator = "libappindicator"
aarch = "aarch"
itor = "itor"
